name: Update configs and commit changes

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 18 * * 1'
  workflow_dispatch:
    inputs:
      name:
        description: 'Description'
        required: false
        default: 'Manually triggered workflow'

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Update repo with changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"
        git clone https://github.com/edgorman/edgorman.github.io
        cd edgorman.github.io
        ./sbin/generateSubmodules.sh
        ./sbin/generateFileSystem.sh
        ./sbin/generateGitHistory.sh
        git add .
        git commit -m "Automatic update (via workflow)"
        git remote set-url --push origin https://edgorman:$GITHUB_TOKEN@github.com/edgorman/edgorman.github.io
        git push
